### ISSUE TITLE
Package.swift not found

### ISSUE THREAD

**Issue by RScottLewis** [erica/trash#1]
Tried both installs and it returned the aforesaid error. FYI

**Comment by erica** [comment]
Just tried, just in case

```
ericasadun% mint install erica/trash
🌱 Finding latest version of trash
🌱 Cloning trash 0.0.1
🌱 Resolving package
🌱 Building package
🌱 Installed trash 0.0.1
🌱 Linked trash 0.0.1 to /usr/local/bin
ericasadun% 
```

Are you using `mint`? Do you get the same issue with other packages? Can you drop me some screenshots or text copies? 

Thank you for opening this issue @RScottLewis

**Comment by RScottLewis** [comment]
Wow, thanks for the fast response. Attached is a view of what happened.FYI

**Comment by erica** [comment]
@RScottLewis I'm not seeing the screenshot on Github. I edited your comment above because it showed your personal contact info, which I'm pretty sure you didn't want to share.

**Comment by RScottLewis** [comment]
Thanks. You could try using the relative address for the Package.swift file
and commit again.

**Comment by RScottLewis** [comment]
Removed: bitcoin spam.

**Comment by erica** [comment]
Edited your replies again. I think you're responding by email and not on github, which is why your personal contact details are showing up.

Can you drop a screenshot into Github and not send by mail please?

**Comment by erica** [comment]
Also I see Package.swift on github and when I clone to my Mac, I also see Package.swift

![Screen Shot 2020-07-12 at 12 08 11 PM](https://user-images.githubusercontent.com/32688/87253435-67fbf680-c438-11ea-8421-0da33777787c.png)

**Comment by erica** [comment]
Also ran ls-files:

```
trash% git ls-files
CHANGELOG.md
LICENSE.txt
Package.swift
README.md
trash.xcodeproj/project.pbxproj
trash/main.swift
```

**Comment by RScottLewis** [comment]
Rather than using mint, I opened your project with xcode. I then change the project to my signing to my account and it worked fine. Thanks.

**Comment by erica** [comment]
Okay, thank you for following up.

Closing!
